REM  The following lines should be placed in CONFIG.SYS
REM  IOPL=YES
REM  C:\COBOL\BINP;. should be added to LIBPATH
PATH=C:\COBOL\BINB;C:\COBOL\BINP;%PATH%
SET COBDIR=C:\COBOL\BINB;C:\COBOL\BINP
SET LIB=C:\COBOL\LIB;%LIB%
SET COBHNF=C:\COBOL\HELP
SET INCLUDE=C:\COBOL\SOURCE;%INCLUDE%
SET HELPFILES=C:\COBOL\HELP;%HELPFILES%
SET INIT=C:\COBOL\INIT;%INIT%
